[package]
name = "dont"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cfg-if = "1.0.0"
clap = { version = "3.1.6", features = ["derive"] }
which = "4.2.4"

[dev-dependencies]
mockall = "0.11.0"
